In [1]:
import gym

In [2]:
import numpy as np
import random
import time
from IPython.display import clear_output

In [3]:
#to craete environment,we call gym.make() and pass a string of the name of the environment
env=gym.make("FrozenLake-v0")

In [4]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table =np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#total number of epsiode the agent want to play during the training
num_episodes=10000
#max num of seps that our agent is allowed to take within a single episode
max_steps_per_episode=100

#mathematically shown using symbol alpha
learning_rate=0.1
#discount rate represented in symbol gamma
discount_rate=0.99

#exploration and exploitation trade-off => epsilon greedy policy
#exploration symbol epsilon 
exploration_rate=1
#the min and max just bounds to how large or small our exploration rate can be
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [6]:
#we create this list to hold all of the rewards we’ll get from each episode
rewards_all_episodes = []

In [15]:
#This first for-loop contains everything that happens within a single episode.
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    #This second nested loop contains everything that happens for a single time-step.
    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) #exploit
        else:
            action = env.action_space.sample()#explore
        #taking action
        #we want to call the step () by passing our action and create the new tuples new_state, reward, done, info (diagnostic information regarding our environment)
        new_state, reward, done, info = env.step(action)
        # Update Q-table for Q(s,a)
        #new key value          #old key value            
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
                       #learned value
        #Transition to next state    
        state = new_state
        rewards_current_episode += reward
        if done == True:
            break
        # Exploration rate decay
        #we need to update our exploration_rate using exponential decay, which just means that the exploration rate decreases or decays at a rate proportional to its current value.
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)


In [16]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

ValueError: array split does not result in an equal division

In [13]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)




********Q-table********

[[0.52080063 0.48626437 0.50916387 0.50425743]
 [0.37084508 0.33628256 0.37399683 0.48632087]
 [0.39405635 0.3940575  0.38089194 0.46081903]
 [0.23749167 0.28238098 0.22590488 0.44872895]
 [0.54162204 0.46624505 0.26449678 0.33080423]
 [0.         0.         0.         0.        ]
 [0.40200066 0.17077948 0.1991728  0.0568537 ]
 [0.         0.         0.         0.        ]
 [0.2959871  0.34751138 0.48659864 0.60234024]
 [0.55303583 0.64837707 0.55414305 0.40398106]
 [0.61774137 0.34702404 0.33590713 0.32361551]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.61895479 0.47169383 0.7778737  0.60449007]
 [0.73879633 0.92583992 0.78652355 0.75011149]
 [0.         0.         0.         0.        ]]


In [14]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
                break
                state = new_state
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
